auctions/urls.py
from django.urls import path


from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path("listing/<int:listing_id>", views.view_listing, name="listing"),
    path("<int:user_id>/create_listing", views.create_listing, name="create_listing"),
    path("listing/<int:listing_id>/", views.close_listing, name="close_listing"),

    path("listing/<int:listing_id>/bid", views.bid_add, name="bid"),

    path("<int:user_id>/watchlist", views.watchlist_view, name="watchlist"),
    path("listing/<int:listing_id>/watchlist_add", views.watchlist_add, name="watchlist_add"),
    path("listing/<int:listing_id>/watchlist_remove", views.watchlist_remove, name="watchlist_remove"),
    
    path("listing/<int:listing_id>/comment_add", views.comment_add, name="comment_add"),
    path("listing/<int:listing_id>/comment_view", views.comment_view, name="comment_view"),

    path("categories", views.categories, name="categories"),
    path("category/<int:cat_id>", views.category_listings, name="category_listings"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE
from django.utils import timezone


class User(AbstractUser):
    first_name = models.CharField(max_length=64, blank=True, help_text="Optional")
    last_name = models.CharField(max_length=64, blank=True, help_text="Optional")

    def __str__(self):
        return f"{self.username}"


class Category(models.Model):
    title = models.CharField(max_length=16, default="Other")

    class Meta:
        verbose_name_plural = "categories"
    
    def __str__(self):
        return f"{self.title}"


class Watchlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="watchlist")
    listing = models.ForeignKey("Listing", null=True, on_delete=models.SET_NULL, related_name="watchlist")

    def __str__(self):
        return f"{self.user}: {self.listing}"


class Bid(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="bids")
    size = models.DecimalField(max_digits=16, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    listing = models.ForeignKey("Listing", null=True, on_delete=models.CASCADE, related_name="bids")

    def __str__(self):
        return f"${self.size}"


class Listing(models.Model):
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=256, default="")
    price = models.DecimalField(max_digits=16, decimal_places=2)
    bid = models.ForeignKey(Bid, null=True, blank=True, on_delete=models.SET_NULL, related_name="listings")
    date = models.DateTimeField(auto_now_add=True)
    image = models.URLField(default="", help_text="Provide a URL-link to Image", max_length=500)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, related_name="listings")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="listings")
    active = models.BooleanField(default=True)
    winner = models.CharField(max_length=64, null=True, blank=True)
    
    def __str__(self):
        return (f"{self.title}")


class Comment(models.Model):
    text = models.CharField(max_length=1024)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE, related_name="author")
    date = models.DateTimeField(default=timezone.now)
    listing = models.ForeignKey("Listing", null=True, on_delete=models.CASCADE, related_name="comments")

    def __str__(self):
        return self.text

auctions/forms.py
from django import forms
from django.forms.widgets import Textarea

from .models import Category, Comment, Listing


class ListingForm(forms.ModelForm):
    title = forms.CharField(max_length=64, label="Title")
    description = forms.CharField(max_length=1024, label="Description", empty_value=True)
    price = forms.DecimalField(max_digits=16, decimal_places=2)
    image = forms.URLField(required=False, empty_value="https://gamepedia.cursecdn.com/ragnarok_gamepedia_en/thumb/1/12/Placeholder_location.png/250px-Placeholder_location.png.jpeg?version=6f64f0c9f146d0ecafb9593b2b1c7a7d")
    category = forms.ModelChoiceField(Category.objects.all(), help_text="Choose a Category")

    class Meta:
        model = Listing
        fields = ("title", "description", "price", "image", "category")


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ("text",)
        widgets = {
            "text": Textarea(attrs={'cols': 100, 'rows': 5, 'default': 'Test comment'}),
        }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone

from .models import Category, Comment, Listing, User, Bid, Watchlist
from .forms import ListingForm
from .utils import get_max_bid, is_watched


def index(request):
    context = {
        "listings": Listing.objects.all()
    }
    return render(request, "auctions/index.html", context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required
def create_listing(request, user_id):
    # Create new listing as a logged-in User
    user = User.objects.get(pk=user_id)
    date = timezone.now()

    if request.method == "POST":
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            
            listing = form.save(commit=False)
            listing.user = user
            form.save()
            
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            context = {"form": form}
            return render(request, "auctions/create_listing.html", context)
    else:
        form = ListingForm()

    context = {
        "form": form,
        "user": user, 
        "date": date,
    }
    return render(request, "auctions/create_listing.html", context)


def view_listing(request, listing_id):
    # View existing listing via its page
    listing = Listing.objects.get(pk=listing_id)
    watched = is_watched(request, listing_id)

    context = {"listing": listing, "watched": watched}
    return render(request, "auctions/view_listing.html", context)

@login_required
def close_listing(request, listing_id):
    # If auction is done, mark the listing as closed (inactive), declare the winner 
    listing = Listing.objects.get(pk=listing_id)
    bid_list = Bid.objects.all().filter(listing=listing.id)
    winner = bid_list.last().user.username

    listing.active = False
    listing.winner = winner
    listing.save()

    context = {"listing": listing}
    return render(request, "auctions/view_listing.html", context)

@login_required
def bid_add(request, listing_id):
    # Add a bid to listing (checks for it to be greater than current max bid)
    listing = Listing.objects.get(pk=listing_id)
    max_bid = get_max_bid(listing_id)
    if request.method == "POST":
        bid_price = int(request.POST["bid"])
        context = {"listing": listing, "message_error": "Your bid must be higher that the current price."}

        if not max_bid:
            if bid_price >= int(listing.price):
                bid = Bid(user=request.user, size=bid_price, listing=listing)
                bid.save()
                listing.bid = bid
                listing.save()
                return HttpResponseRedirect(reverse("auctions:listing", args=(listing.id,)))
            else:
                return render(request, "auctions/view_listing.html", context)

        elif max_bid:
            if bid_price > max(int(listing.price), int(max_bid)):
                bid = Bid(user=request.user, size=bid_price, listing_id=listing.id)
                bid.save()
                listing.bid = bid
                listing.save()
                return HttpResponseRedirect(reverse("auctions:listing", args=(listing.id,)))
            else:
                return render(request, "auctions/view_listing.html", context)
    
    else:
        context = {"listing": listing}
        return render(request, "auctions/view_listing.html", context)

@login_required
def watchlist_add(request, listing_id):
    # Add currently viewed listing to logged-in User's watchlist
    listing = Listing.objects.get(pk=listing_id)
    watchlist = Watchlist(user=request.user, listing=listing)
    watchlist.save()

    watchlist_list = Watchlist.objects.all().filter(user=request.user)

    context = {"watchlist": watchlist_list, "listing": listing,}
    return HttpResponseRedirect(reverse("auctions:listing", args=(listing.id,)))

@login_required
def watchlist_remove(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    watchlist = Watchlist.objects.all().filter(user=request.user, listing=listing)
    watchlist.delete()

    watchlist = Watchlist.objects.all().filter(user=request.user, listing=listing)
    
    return HttpResponseRedirect(reverse("auctions:watchlist", args=(request.user.id,)))

@login_required
def watchlist_view(request, user_id):
    watchlist = Watchlist.objects.all().filter(user=request.user)

    context = {"watchlist": watchlist}
    return render(request, "auctions/watchlist.html", context)

@login_required
def comment_add(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    watched = is_watched(request, listing_id)
    if request.method == "POST":
        text = request.POST["text"]
        author  = User.objects.get(pk=request.user.id)
        comment = Comment(text=text, author=author, listing=listing)
        comment.save()
        context = {"listing": listing}
        return HttpResponseRedirect(reverse("auctions:listing", args=(listing.id,)))
    else:
        context = {"listing": listing, "watched": watched}
    
    return render(request, "auctions/view_listing.html", context)


def comment_view(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    comments = Comment.objects.all().filter(listing=listing)

    context = {"comments": comments}
    return HttpResponseRedirect(reverse("auctions:listing", args=(listing.id,)))


def categories(request):
    # Show list of existing categories of listings
    categories = Category.objects.all()

    context = {"categories": categories}
    return render(request, "auctions/categories.html", context)


def category_listings(request, cat_id):
    # Show all listings in the chosen category
    category = Category.objects.get(pk=cat_id)
    cat_listings = Listing.objects.all().filter(category=category)

    context = {"listings": cat_listings, "category": category}
    return render(request, "auctions/category_listings.html", context)

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}

{% block body %}

    <h1>Categories:</h1>

    <br>

    {% for category in categories %}
    
        <ul>
            <a href={% url 'auctions:category_listings' category.id %}><li>{{ category.title }}</li></a>
        </ul>
    
    {% endfor %}

{% endblock body %}

auctions/templates/auctions/category_listings.html
{% extends 'auctions/layout.html' %}

{% block body %}

    <h1>Listings in {{ category.title }} category: </h1>

    {% for listing in listings %}
        {% include 'auctions/display_listing.html' %}
    {% endfor %}

{% endblock body %}

auctions/templates/auctions/close_listing.html
{% ifequal user listing.user %}

    {% if listing.active %}
        <span><a class="btn btn-primary" href="{% url 'auctions:close_listing' listing.id %}">Close Listing</a></span>
    {% endif %}

{% endifequal %}

auctions/templates/auctions/comment_add.html
<form action="{% url 'auctions:comment_add' listing.id %}" method="POST">
    {% csrf_token %}

    {{ form }}
    {% comment %} <textarea cols="100" rows="5" placeholder="Enter comment here"></textarea> {% endcomment %}
    <input type="submit" value="Submit Comment">

</form>

auctions/templates/auctions/create_listing.html
{% extends 'auctions/layout.html' %}

{% block title %}
    Create New Listing
{% endblock %}

{% block body %}
    <form action="{% url 'auctions:create_listing' user.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit Listing">

    </form>
{% endblock %}

auctions/templates/auctions/display_listing.html
{% load static %}

{% if listing.active %}
    <div class="listing-wrapper">
        <div class="listing_title link">
            <a href="{% url 'auctions:listing' listing.id %}" alt="{{ listing.title }}"><h3>{{ listing.title }}</h3></a>
        </div>

        <div class="listing-image">
            {% if listing.image %}
                <div class="listing_image link"><img class="image" src="{{ listing.image }}" alt="{{ listing.title }}"></div>
            {% endif %}
        </div>

        <div>{{ listing.description }}</div>

        <div class="starting_price"><b>Starting price:</b> ${{ listing.price }}</div>

        <div class="bid_info">
            {% if listing.bid %}
                <b>Highest Bid:</b> ${{ listing.bid.size }}
            {% else %}
                <b>Highest Bid:</b> No bids made yet.
            {% endif %}
        </div>

        <div class="listing-author">Listed by: {{ listing.user }}</div>

        <div class="listing-date">Created: {{ listing.date }}</div>
    </div>
{% endif %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
<div class="index_view">
    <h2>Active Listings</h2>
    <div class="listings_all">

    {% for listing in listings %}
        {% include 'auctions/display_listing.html' %}
    {% endfor %}
    </div>
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="body-content-wrapper">
            <h1>Auctions</h1>
            <div>
                {% if user.is_authenticated %}
                    Signed in as <strong>{{ user.username }}</strong>.
                {% else %}
                    Not signed in.
                {% endif %}
            </div>
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link btn btn-primary" href="{% url 'auctions:index' %}">Active Listings</a>
                </li>
    
                <li class="nav-item">
                    <a class="nav-link btn btn-primary" href={% url 'auctions:categories' %}>Categories</a>
                </li>
                
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link btn btn-primary" href={% url "auctions:watchlist" user_id=user.id %}>My Watchlist</a>
                    </li>
    
                    <li class="nav-item">
                        <a class="nav-link btn btn-primary" href="{% url "auctions:create_listing" user_id=user.id %}">Create New Listing</a>
                    </li>
    
                    <li class="nav-item">
                        <a class="nav-link btn btn-warning" href="{% url 'auctions:logout' %}">Log Out</a>
                    </li>
    
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link btn btn-primary" href="{% url 'auctions:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-primary" href="{% url 'auctions:register' %}">Register</a>
                    </li>
    
                {% endif %}
            </ul>
            <hr>
            <div class="body_block">
                {% block body %}{% endblock %}
            </div>
        </div>
        <footer class="footer footer-wrapper">
            <div class="footer content-wrapper">
                <div class="footer footer-text">Author: Konstantine D.</div>
                <div class="footer footer-link">
                    <a href="https://github.com/KonstantineDM" alt="Link to author's Github page">Github</a>
            </div>
        </footer>
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="first_name" placeholder="First Name">
            <label for="first_name">Optional</label>

        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="last_name" placeholder="Last Name">
            <label for="last_name">Optional</label>
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/view_listing.html
{% extends 'auctions/layout.html' %}

{% block title %}
    {{ listing.title }}
{% endblock %}

{% block body %}

    <div><h1>{{ listing.title }}</h1></div>

    {% if not listing.active %}
        {% if listing.winner %}
            <h2>Listing is closed. The winner is: {{ listing.winner }}.
        {% endif %}
    {% endif %}

    <div><img src="{{ listing.image }}" class="image" alt="Image of {{ listing.description }}"></div>

    <div><h5>Description: {{ listing.description }}</h5></div>

    {% if listing.bid %}
        <div>Current price: ${{ listing.bid.size }}</div>
    {% else %}
        <div>Current price: ${{ listing.price }}</div>
    {%endif %}

    <div><h5>Details</h5></div>
    <ul>
        <li>Listed by: {{ listing.user }}</li>
        <li>Category: {{ listing.category }}</li>
    </ul>

    {% if user.is_authenticated %}
        {% if not listing.winner %}
            <h4>Make a new bid (should be greater than current price)</h4>
            <form action="{% url 'auctions:bid' listing.id %}" method="POST">
                {% csrf_token %}
                <input type="text" name="bid" placeholder="Enter bid size, $" size=20>
                <input type="submit" value="Make a bid">
                <div>
                    {% if message_error %}
                        {{ message_error }}
                    {% endif %}
                </div>
            </form>
        {% endif %}
    {% else %}
        <div>To make a bid you must be logged in.</div>
    {% endif %}

    {% if user.is_authenticated %}
        {% if not watched %}
            <div>
                <span><a type="button" class="btn btn-primary" 
                       href="{% url 'auctions:watchlist_add' listing_id=listing.id %}">
                       Add to Watchlist</a></span>
            </div>
        {% else %}
            <div>
                <span class="btn btn-secondary">In Watchlist</span>
            </div>
        {% endif %}

        {% include "auctions/close_listing.html" %}

        <form action="{% url 'auctions:comment_add' listing.id %}" method="POST">
            {% csrf_token %}

            <textarea name="text" cols="100" rows="5" placeholder="Enter comment here"></textarea>
            <input type="submit" value="Submit Comment">

        </form>
    {% endif %}

    <h3>Comments</h3>
    {% for comment in listing.comments.all %}
        <div>{{ comment.text }}</div>
        <div>{{ comment.author }}</div>
        <div>{{ comment.date }}</div>

    {% empty %}
        <div>No comments yet</div>
    
    {% endfor %}
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}

{% block title %}My Watchlist{% endblock title %}

{% block body %}

    <div><h3>My Watchlist</h3></div>

    {% if watchlist %}
        {% for item in watchlist %}

            <ul>
                <li>
                    <div>
                        <a href={% url 'auctions:listing' listing_id=item.listing.id%}>{{ item.listing.title }}</a>
                        : starting price ${{ item.listing.price}} / highest bid {{ item.listing.bid }}
                    </div>

                    <div>
                        <a class="nav-link btn btn-primary" href="{% url 'auctions:watchlist_remove' item.listing.id %}" 
                            alt="Remove from Wathclist">Remove from Watchlist</a>
                    </div>
                </li>
            </ul>
            
        {% endfor %}
    {% else %}
        <div>No items added to Watchlist yet.</div>
    {% endif %}
    
{% endblock body %}